name: Publish Docker image

on:
  push:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
     
      - name: Log in to Docker
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Server build
        run: |
          docker build ./back-end --tag jessewu10/bison-bank-of-canada:server
      - name: Docker push
        run: |
          docker push jessewu10/bison-bank-of-canada:server
        
      - name: Docker Client build
        run: |
          docker build ./front-end --tag jessewu10/bison-bank-of-canada:client
      - name: Docker push
        run: |
          docker push jessewu10/bison-bank-of-canada:client